[build]
  publish = "site"
  command = "npm run build:css"

[build.processing]
  skip_processing = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
